safe: true
lsi: false
pygments: true
markdown: redcarpet
auto: true
title: "KilGame-互动娱乐"
public_url: "http://kilgame.github.com"
keywords: "android,xml,html,JavaScript,css,Github"
owner:
  name: "KilGame"
  mail: "tofro@qq.com"
disqus:
  short_name: "KilGame"
paginate: 10
exclude: [start-jekyll.bat, Github.sln, Github.v11.suo]